import { processDetailSchema, processEventSchema, processesAdminSchema } from '@/lib/schemas';

// Demo-friendly sample payloads used when API is unavailable or returns errors.
// Keeps UI populated without needing unsafe eval or inline JS.
export const sampleProcessesAdmin = processesAdminSchema.parse([
  {
    id: 'prc_demo_ready',
    account_opening_id: 'acc_demo_01',
    phone: '+50255501111',
    name: 'Juana Demo',
    status: 'ready_for_bank',
    banking_status: 'bank_processing',
    verification_status: 'phone_verified',
    attempts: 2,
    events_count: 6,
    last_error: null,
    steps: 5,
    usage: 12,
    product_type: 'Cuenta digital',
    account_currency: 'GTQ',
    updated_at: '2025-01-15T12:05:00Z',
    correlation_id: 'corr-demo-123',
    meta: { source: 'sample' },
  },
  {
    id: 'prc_demo_retry',
    account_opening_id: 'acc_demo_02',
    phone: '+50255502222',
    name: 'Carlos Sample',
    status: 'bank_retry',
    banking_status: 'bank_retry',
    verification_status: 'review_required',
    attempts: 4,
    events_count: 8,
    last_error: 'Timeout en core bancario',
    steps: 7,
    usage: 18,
    product_type: 'Crédito simple',
    account_currency: 'USD',
    updated_at: '2025-01-15T11:40:00Z',
    correlation_id: 'corr-demo-456',
    meta: { source: 'sample' },
  },
]);

import { z } from 'zod';

type SampleProcessDetail = z.infer<typeof processDetailSchema>;
type SampleProcessEvent = z.infer<typeof processEventSchema>;

const sampleProcessDetailsMap: Record<string, SampleProcessDetail> = {
  prc_demo_ready: processDetailSchema.parse({
    ...sampleProcessesAdmin[0],
    account: {
      id: 'acc_demo_01',
      full_name: 'Juana Demo',
      birth_date: '1994-03-12',
      gender: 'F',
      nationality: 'Guatemala',
      marital_status: 'Soltera',
      email: 'juana.demo@example.com',
      phone_main: '+50255501111',
      phone_secondary: '+50255501112',
      whatsapp_phone_e164: '+50255501111',
      address_full: '14 Avenida 12-30, Zona 10, Guatemala',
      address_city: 'Guatemala',
      address_state: 'Guatemala',
      address_country: 'GT',
      address_housing_type: 'Propia',
      employment_status: 'Empleado',
      employer_name: 'ACME Corp',
      monthly_income: 7200,
      monthly_expenses: 2800,
      other_income_sources: 'Remesas',
      document_type: 'DPI',
      document_number: '1234567890101',
      document_country: 'GT',
      product_type: 'Cuenta digital',
      account_currency: 'GTQ',
      renap_status: 'ok',
      renap_citizen_data: {
        citizen_data: [
          {
            cui: '1234567890101',
            primer_nombre: 'Juana',
            segundo_nombre: 'María',
            primer_apellido: 'Demo',
            segundo_apellido: 'García',
            fecha_nacimiento: '1994-03-12',
            nacionalidad: 'Guatemala',
            estado_civil: 'Soltera',
            vecindad: 'Guatemala',
            fecha_vencimiento: '2030-01-01',
          },
        ],
      },
      phone_verification_status: 'verified',
      phone_verification_metadata: { verified_at: '2025-01-15T11:50:00Z' },
      qic_status: 'clear',
      didit_status: 'clear',
      didit_verification_link: 'https://verify.example.com/session/demo',
      didit_last_check: '2025-01-15T11:48:00Z',
      renap_last_check: '2025-01-15T11:46:00Z',
      verification_started_at: '2025-01-15T11:40:00Z',
      verification_completed_at: '2025-01-15T11:52:00Z',
      is_pep: false,
      is_pep_related: false,
      has_us_tax_obligations: false,
      compliance_checks_raw: ['pepCheck:clear'],
      extra_data: {
        complete_flow_data: {
          estado_civil: 'Soltera',
          nacionalidad: 'Guatemala',
          tipo_vivienda: 'Propia',
          direccion_completa: '14 Avenida 12-30, Zona 10, Guatemala',
          correo_electronico: 'juana.demo@example.com',
          nombre_empresa: 'ACME Corp',
          relacion_laboral: 'Empleado',
          ingresos_mensuales: '7200',
          egresos_mensuales: '2800',
          compliance_checks: 'pepCheck:clear',
        },
      },
      bank_blacklist_finished_at: '2025-01-15T11:30:00Z',
      bank_onboarding_finished_at: '2025-01-15T11:45:00Z',
      bank_account_finished_at: null,
      bank_complementary_finished_at: '2025-01-15T11:55:00Z',
    },
    timeline: [
      {
        id: 'evt_demo_01',
        type: 'verification',
        status: 'ok',
        step: 'documento',
        message: 'Documento validado',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:42:00Z',
        payload: { source: 'didit' },
      },
      {
        id: 'evt_demo_02',
        type: 'verification',
        status: 'ok',
        step: 'renap',
        message: 'RENAP coincide',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:46:00Z',
        payload: { match: true },
      },
      {
        id: 'evt_demo_03',
        type: 'bank',
        status: 'processing',
        step: 'blacklist',
        message: 'Enviada a blacklist',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:50:00Z',
      },
      {
        id: 'evt_demo_04',
        type: 'bank',
        status: 'processing',
        step: 'onboarding',
        message: 'Onboarding iniciado',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:52:00Z',
      },
    ],
    banking_events: [
      {
        id: 'evt_demo_bank_01',
        type: 'bank',
        status: 'processing',
        step: 'blacklist',
        message: 'Blacklist clear',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:30:00Z',
        payload: { result: 'clear' },
      },
      {
        id: 'evt_demo_bank_02',
        type: 'bank',
        status: 'processing',
        step: 'onboarding',
        message: 'Onboarding enviado',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:45:00Z',
        payload: { account_type: 'Cuenta digital' },
      },
    ],
  }),
  prc_demo_retry: processDetailSchema.parse({
    ...sampleProcessesAdmin[1],
    account: {
      id: 'acc_demo_02',
      full_name: 'Carlos Sample',
      birth_date: '1990-07-22',
      gender: 'M',
      nationality: 'Guatemala',
      marital_status: 'Casado',
      email: 'carlos.sample@example.com',
      phone_main: '+50255502222',
      address_full: '6a Avenida 4-55, Zona 14, Guatemala',
      address_city: 'Guatemala',
      address_state: 'Guatemala',
      address_country: 'GT',
      employment_status: 'Independiente',
      employer_name: 'Consultor',
      monthly_income: 5200,
      monthly_expenses: 3100,
      document_type: 'DPI',
      document_number: '1098765432101',
      document_country: 'GT',
      renap_status: 'ok',
      renap_citizen_data: {
        citizen_data: [
          {
            cui: '1098765432101',
            primer_nombre: 'Carlos',
            primer_apellido: 'Sample',
            fecha_nacimiento: '1990-07-22',
            nacionalidad: 'Guatemala',
            estado_civil: 'Casado',
            fecha_vencimiento: '2029-07-22',
          },
        ],
      },
      phone_verification_status: 'retry',
      phone_verification_metadata: { verified_at: null },
      qic_status: 'pending',
      didit_status: 'manual_review',
      renap_last_check: '2025-01-15T11:20:00Z',
      verification_started_at: '2025-01-15T11:00:00Z',
      verification_completed_at: null,
      is_pep: false,
      is_pep_related: false,
      has_us_tax_obligations: false,
      compliance_checks_raw: ['pepCheck:clear'],
      extra_data: {
        complete_flow_data: {
          estado_civil: 'Casado',
          nacionalidad: 'Guatemala',
          tipo_vivienda: 'Rentada',
          direccion_completa: '6a Avenida 4-55, Zona 14, Guatemala',
          correo_electronico: 'carlos.sample@example.com',
          ingresos_mensuales: '5200',
          egresos_mensuales: '3100',
          compliance_checks: 'pepCheck:clear',
        },
      },
      bank_blacklist_finished_at: '2025-01-15T11:05:00Z',
      bank_onboarding_finished_at: null,
      bank_account_finished_at: null,
      bank_complementary_finished_at: null,
    },
    timeline: [
      {
        id: 'evt_demo_05',
        type: 'verification',
        status: 'warn',
        step: 'didit',
        message: 'Documento borroso, requiere retry',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:10:00Z',
        payload: { attempt: 1 },
      },
      {
        id: 'evt_demo_06',
        type: 'verification',
        status: 'warn',
        step: 'otp',
        message: 'OTP no contestado',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:18:00Z',
      },
      {
        id: 'evt_demo_07',
        type: 'bank',
        status: 'retry',
        step: 'onboarding',
        message: 'Banco pidió retry',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:35:00Z',
      },
    ],
    banking_events: [
      {
        id: 'evt_demo_bank_03',
        type: 'bank',
        status: 'retry',
        step: 'onboarding',
        message: 'Campos faltantes',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:34:00Z',
        payload: { missing: ['address_full'] },
      },
    ],
  }),
};

const sampleProcessEventsMap: Record<string, SampleProcessEvent[]> = {
  prc_demo_ready: sampleProcessDetailsMap.prc_demo_ready.timeline || [],
  prc_demo_retry: sampleProcessDetailsMap.prc_demo_retry.timeline || [],
};

export const sampleProcessDetailById = (id?: string) => {
  const detail = id ? sampleProcessDetailsMap[id] : undefined;
  if (detail) return detail;
  return sampleProcessDetailsMap.prc_demo_ready;
};

export const sampleProcessEventsById = (id?: string) => {
  const events = id ? sampleProcessEventsMap[id] : undefined;
  if (events) return events;
  return sampleProcessEventsMap.prc_demo_ready;
};

