import { processDetailSchema, processEventSchema, processesAdminSchema } from '@/lib/schemas';

// Demo-friendly sample payloads used when API is unavailable or returns errors.
// Keeps UI populated without needing unsafe eval or inline JS.
export const sampleProcessesAdmin = processesAdminSchema.parse([
  {
    id: 'prc_gt_001',
    account_opening_id: 'acc_gt_01',
    phone: '+50255501111',
    whatsapp_phone_e164: '+50255501111',
    name: 'María González',
    status: 'ready_for_bank',
    banking_status: 'bank_processing',
    verification_status: 'didit_verified',
    attempts: 1,
    events_count: 4,
    last_error: null,
    product_type: 'Cuenta Digital',
    account_currency: 'GTQ',
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    correlation_id: 'gt-corr-001',
  },
  {
    id: 'prc_br_001',
    account_opening_id: 'acc_br_01',
    phone: '+5511984129269',
    whatsapp_phone_e164: '+5511984129269',
    name: null,
    status: 'bank_processing',
    banking_status: 'bank_processing',
    verification_status: 'didit_verified',
    attempts: 0,
    events_count: 2,
    last_error: null,
    product_type: 'Conta Corrente',
    account_currency: 'BRL',
    updated_at: new Date(Date.now() - 1000 * 60 * 16).toISOString(),
    correlation_id: 'c0f2-a9a7',
  },
  {
    id: 'prc_gt_002',
    account_opening_id: 'acc_gt_02',
    phone: '+50244447777',
    whatsapp_phone_e164: '+50244447777',
    name: 'Carlos Mendoza',
    status: 'bank_retry',
    banking_status: 'bank_retry',
    verification_status: 'phone_verified',
    attempts: 3,
    events_count: 12,
    last_error: 'Core bancario timeout - reintentar',
    product_type: 'Crédito Simple',
    account_currency: 'GTQ',
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    correlation_id: 'gt-corr-002',
  },
  {
    id: 'prc_br_002',
    account_opening_id: 'acc_br_02',
    phone: '+5521999887766',
    whatsapp_phone_e164: '+5521999887766',
    name: 'Ana Paula Silva',
    status: 'account_created',
    banking_status: 'account_created',
    verification_status: 'didit_verified',
    attempts: 1,
    events_count: 8,
    last_error: null,
    product_type: 'Conta Digital',
    account_currency: 'BRL',
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    correlation_id: 'br-corr-002',
  },
  {
    id: 'prc_gt_003',
    account_opening_id: 'acc_gt_03',
    phone: '+50233338888',
    whatsapp_phone_e164: '+50233338888',
    name: null,
    status: 'bank_rejected',
    banking_status: 'bank_rejected',
    verification_status: 'review_required',
    attempts: 5,
    events_count: 15,
    last_error: 'Cliente en lista negra del banco',
    product_type: 'Tarjeta Crédito',
    account_currency: 'USD',
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    correlation_id: 'gt-corr-003',
  },
]);

import { z } from 'zod';

type SampleProcessDetail = z.infer<typeof processDetailSchema>;
type SampleProcessEvent = z.infer<typeof processEventSchema>;

const sampleProcessDetailsMap: Record<string, SampleProcessDetail> = {
  prc_demo_ready: processDetailSchema.parse({
    ...sampleProcessesAdmin[0],
    account: {
      id: 'acc_demo_01',
      full_name: 'Juana Demo',
      birth_date: '1994-03-12',
      gender: 'F',
      nationality: 'Guatemala',
      marital_status: 'Soltera',
      email: 'juana.demo@example.com',
      phone_main: '+50255501111',
      phone_secondary: '+50255501112',
      whatsapp_phone_e164: '+50255501111',
      address_full: '14 Avenida 12-30, Zona 10, Guatemala',
      address_city: 'Guatemala',
      address_state: 'Guatemala',
      address_country: 'GT',
      address_housing_type: 'Propia',
      employment_status: 'Empleado',
      employer_name: 'ACME Corp',
      monthly_income: 7200,
      monthly_expenses: 2800,
      other_income_sources: 'Remesas',
      document_type: 'DPI',
      document_number: '1234567890101',
      document_country: 'GT',
      product_type: 'Cuenta digital',
      account_currency: 'GTQ',
      renap_status: 'ok',
      renap_citizen_data: {
        citizen_data: [
          {
            cui: '1234567890101',
            primer_nombre: 'Juana',
            segundo_nombre: 'María',
            primer_apellido: 'Demo',
            segundo_apellido: 'García',
            fecha_nacimiento: '1994-03-12',
            nacionalidad: 'Guatemala',
            estado_civil: 'Soltera',
            vecindad: 'Guatemala',
            fecha_vencimiento: '2030-01-01',
          },
        ],
      },
      phone_verification_status: 'verified',
      phone_verification_metadata: { verified_at: '2025-01-15T11:50:00Z' },
      qic_status: 'clear',
      didit_status: 'clear',
      didit_verification_link: 'https://verify.example.com/session/demo',
      didit_last_check: '2025-01-15T11:48:00Z',
      renap_last_check: '2025-01-15T11:46:00Z',
      verification_started_at: '2025-01-15T11:40:00Z',
      verification_completed_at: '2025-01-15T11:52:00Z',
      is_pep: false,
      is_pep_related: false,
      has_us_tax_obligations: false,
      compliance_checks_raw: ['pepCheck:clear'],
      extra_data: {
        complete_flow_data: {
          estado_civil: 'Soltera',
          nacionalidad: 'Guatemala',
          tipo_vivienda: 'Propia',
          direccion_completa: '14 Avenida 12-30, Zona 10, Guatemala',
          correo_electronico: 'juana.demo@example.com',
          nombre_empresa: 'ACME Corp',
          relacion_laboral: 'Empleado',
          ingresos_mensuales: '7200',
          egresos_mensuales: '2800',
          compliance_checks: 'pepCheck:clear',
        },
      },
      bank_blacklist_finished_at: '2025-01-15T11:30:00Z',
      bank_onboarding_finished_at: '2025-01-15T11:45:00Z',
      bank_account_finished_at: null,
      bank_complementary_finished_at: '2025-01-15T11:55:00Z',
    },
    timeline: [
      {
        id: 'evt_demo_01',
        type: 'verification',
        status: 'ok',
        step: 'documento',
        message: 'Documento validado',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:42:00Z',
        payload: { source: 'didit' },
      },
      {
        id: 'evt_demo_02',
        type: 'verification',
        status: 'ok',
        step: 'renap',
        message: 'RENAP coincide',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:46:00Z',
        payload: { match: true },
      },
      {
        id: 'evt_demo_03',
        type: 'bank',
        status: 'processing',
        step: 'blacklist',
        message: 'Enviada a blacklist',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:50:00Z',
      },
      {
        id: 'evt_demo_04',
        type: 'bank',
        status: 'processing',
        step: 'onboarding',
        message: 'Onboarding iniciado',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:52:00Z',
      },
    ],
    banking_events: [
      {
        id: 'evt_demo_bank_01',
        type: 'bank',
        status: 'processing',
        step: 'blacklist',
        message: 'Blacklist clear',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:30:00Z',
        payload: { result: 'clear' },
      },
      {
        id: 'evt_demo_bank_02',
        type: 'bank',
        status: 'processing',
        step: 'onboarding',
        message: 'Onboarding enviado',
        correlation_id: 'corr-demo-123',
        created_at: '2025-01-15T11:45:00Z',
        payload: { account_type: 'Cuenta digital' },
      },
    ],
  }),
  prc_demo_retry: processDetailSchema.parse({
    ...sampleProcessesAdmin[1],
    account: {
      id: 'acc_demo_02',
      full_name: 'Carlos Sample',
      birth_date: '1990-07-22',
      gender: 'M',
      nationality: 'Guatemala',
      marital_status: 'Casado',
      email: 'carlos.sample@example.com',
      phone_main: '+50255502222',
      address_full: '6a Avenida 4-55, Zona 14, Guatemala',
      address_city: 'Guatemala',
      address_state: 'Guatemala',
      address_country: 'GT',
      employment_status: 'Independiente',
      employer_name: 'Consultor',
      monthly_income: 5200,
      monthly_expenses: 3100,
      document_type: 'DPI',
      document_number: '1098765432101',
      document_country: 'GT',
      renap_status: 'ok',
      renap_citizen_data: {
        citizen_data: [
          {
            cui: '1098765432101',
            primer_nombre: 'Carlos',
            primer_apellido: 'Sample',
            fecha_nacimiento: '1990-07-22',
            nacionalidad: 'Guatemala',
            estado_civil: 'Casado',
            fecha_vencimiento: '2029-07-22',
          },
        ],
      },
      phone_verification_status: 'retry',
      phone_verification_metadata: { verified_at: null },
      qic_status: 'pending',
      didit_status: 'manual_review',
      renap_last_check: '2025-01-15T11:20:00Z',
      verification_started_at: '2025-01-15T11:00:00Z',
      verification_completed_at: null,
      is_pep: false,
      is_pep_related: false,
      has_us_tax_obligations: false,
      compliance_checks_raw: ['pepCheck:clear'],
      extra_data: {
        complete_flow_data: {
          estado_civil: 'Casado',
          nacionalidad: 'Guatemala',
          tipo_vivienda: 'Rentada',
          direccion_completa: '6a Avenida 4-55, Zona 14, Guatemala',
          correo_electronico: 'carlos.sample@example.com',
          ingresos_mensuales: '5200',
          egresos_mensuales: '3100',
          compliance_checks: 'pepCheck:clear',
        },
      },
      bank_blacklist_finished_at: '2025-01-15T11:05:00Z',
      bank_onboarding_finished_at: null,
      bank_account_finished_at: null,
      bank_complementary_finished_at: null,
    },
    timeline: [
      {
        id: 'evt_demo_05',
        type: 'verification',
        status: 'warn',
        step: 'didit',
        message: 'Documento borroso, requiere retry',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:10:00Z',
        payload: { attempt: 1 },
      },
      {
        id: 'evt_demo_06',
        type: 'verification',
        status: 'warn',
        step: 'otp',
        message: 'OTP no contestado',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:18:00Z',
      },
      {
        id: 'evt_demo_07',
        type: 'bank',
        status: 'retry',
        step: 'onboarding',
        message: 'Banco pidió retry',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:35:00Z',
      },
    ],
    banking_events: [
      {
        id: 'evt_demo_bank_03',
        type: 'bank',
        status: 'retry',
        step: 'onboarding',
        message: 'Campos faltantes',
        correlation_id: 'corr-demo-456',
        created_at: '2025-01-15T11:34:00Z',
        payload: { missing: ['address_full'] },
      },
    ],
  }),
};

const sampleProcessEventsMap: Record<string, SampleProcessEvent[]> = {
  prc_demo_ready: sampleProcessDetailsMap.prc_demo_ready.timeline || [],
  prc_demo_retry: sampleProcessDetailsMap.prc_demo_retry.timeline || [],
};

export const sampleProcessDetailById = (id?: string) => {
  const detail = id ? sampleProcessDetailsMap[id] : undefined;
  if (detail) return detail;
  return sampleProcessDetailsMap.prc_demo_ready;
};

export const sampleProcessEventsById = (id?: string) => {
  const events = id ? sampleProcessEventsMap[id] : undefined;
  if (events) return events;
  return sampleProcessEventsMap.prc_demo_ready;
};

// Sample Conversations
import { conversationListSchema, conversationDetailSchema } from '@/lib/schemas';

export const sampleConversations = conversationListSchema.parse([
  {
    id: 'conv_demo_01',
    name: 'María García',
    product: 'Cuenta digital',
    status: 'activa',
    unread: 2,
    updatedAt: '2025-01-15T14:30:00Z',
    tags: ['vip', 'onboarding'],
  },
  {
    id: 'conv_demo_02',
    name: 'Juan Pérez',
    product: 'Crédito simple',
    status: 'pendiente',
    unread: 0,
    updatedAt: '2025-01-15T13:15:00Z',
    tags: ['soporte'],
  },
  {
    id: 'conv_demo_03',
    name: 'Ana López',
    product: 'Tarjeta débito',
    status: 'activa',
    unread: 1,
    updatedAt: '2025-01-15T12:45:00Z',
    tags: ['consulta'],
  },
  {
    id: 'conv_demo_04',
    name: 'Roberto Méndez',
    product: 'Cuenta empresarial',
    status: 'en espera',
    unread: 0,
    updatedAt: '2025-01-15T11:20:00Z',
    tags: ['pyme'],
  },
]);

const sampleConversationDetailsMap: Record<string, z.infer<typeof conversationDetailSchema>> = {
  conv_demo_01: conversationDetailSchema.parse({
    id: 'conv_demo_01',
    name: 'María García',
    product: 'Cuenta digital',
    status: 'activa',
    phone: '+50255501234',
    unread: 2,
    tags: ['vip', 'onboarding'],
    proceso: 'Apertura de cuenta',
    progreso: '75%',
    assignedTo: 'Agente Carlos',
    messages: [
      { id: 'msg_01', from: 'María García', body: 'Hola, necesito ayuda con mi cuenta', at: '2025-01-15T14:00:00Z', direction: 'in' },
      { id: 'msg_02', from: 'agent', body: 'Hola María, con gusto te ayudo. ¿Cuál es tu consulta?', at: '2025-01-15T14:02:00Z', direction: 'out' },
      { id: 'msg_03', from: 'María García', body: 'No puedo ver mi saldo en la app', at: '2025-01-15T14:05:00Z', direction: 'in' },
      { id: 'msg_04', from: 'agent', body: 'Entiendo, déjame verificar tu cuenta. ¿Me puedes confirmar tu número de documento?', at: '2025-01-15T14:07:00Z', direction: 'out' },
      { id: 'msg_05', from: 'María García', body: '1234567890101', at: '2025-01-15T14:10:00Z', direction: 'in' },
    ],
  }),
  conv_demo_02: conversationDetailSchema.parse({
    id: 'conv_demo_02',
    name: 'Juan Pérez',
    product: 'Crédito simple',
    status: 'pendiente',
    phone: '+50255505678',
    unread: 0,
    tags: ['soporte'],
    proceso: 'Solicitud de crédito',
    progreso: '40%',
    assignedTo: 'Agente Ana',
    messages: [
      { id: 'msg_06', from: 'Juan Pérez', body: 'Quisiera información sobre créditos', at: '2025-01-15T13:00:00Z', direction: 'in' },
      { id: 'msg_07', from: 'agent', body: 'Claro Juan, tenemos varias opciones. ¿Cuánto necesitas y en qué plazo?', at: '2025-01-15T13:05:00Z', direction: 'out' },
      { id: 'msg_08', from: 'Juan Pérez', body: 'Unos Q10,000 a 12 meses', at: '2025-01-15T13:10:00Z', direction: 'in' },
    ],
  }),
  conv_demo_03: conversationDetailSchema.parse({
    id: 'conv_demo_03',
    name: 'Ana López',
    product: 'Tarjeta débito',
    status: 'activa',
    phone: '+50255509012',
    unread: 1,
    tags: ['consulta'],
    proceso: 'Activación de tarjeta',
    progreso: '90%',
    assignedTo: 'Agente Pedro',
    messages: [
      { id: 'msg_09', from: 'Ana López', body: 'Mi tarjeta no funciona en el ATM', at: '2025-01-15T12:30:00Z', direction: 'in' },
      { id: 'msg_10', from: 'agent', body: 'Hola Ana, verifico el estado de tu tarjeta', at: '2025-01-15T12:32:00Z', direction: 'out' },
      { id: 'msg_11', from: 'agent', body: 'Tu tarjeta requiere activación. Te envío el código por SMS', at: '2025-01-15T12:35:00Z', direction: 'out' },
      { id: 'msg_12', from: 'Ana López', body: 'Listo, ya la activé. Gracias!', at: '2025-01-15T12:40:00Z', direction: 'in' },
    ],
  }),
  conv_demo_04: conversationDetailSchema.parse({
    id: 'conv_demo_04',
    name: 'Roberto Méndez',
    product: 'Cuenta empresarial',
    status: 'en espera',
    phone: '+50255503456',
    unread: 0,
    tags: ['pyme'],
    proceso: 'Apertura cuenta empresarial',
    progreso: '25%',
    assignedTo: 'Agente María',
    messages: [
      { id: 'msg_13', from: 'Roberto Méndez', body: 'Necesito abrir una cuenta para mi empresa', at: '2025-01-15T11:00:00Z', direction: 'in' },
      { id: 'msg_14', from: 'agent', body: 'Hola Roberto, con gusto. ¿Qué tipo de empresa es?', at: '2025-01-15T11:05:00Z', direction: 'out' },
      { id: 'msg_15', from: 'Roberto Méndez', body: 'Es una sociedad anónima, tenemos 3 años operando', at: '2025-01-15T11:10:00Z', direction: 'in' },
    ],
  }),
};

export const sampleConversationDetailById = (id?: string) => {
  const detail = id ? sampleConversationDetailsMap[id] : undefined;
  if (detail) return detail;
  return sampleConversationDetailsMap.conv_demo_01;
};

